version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    # イメージ名を指定
    image: ghcr.io/toshi0806/docker-atcoder:latest

    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - ../problems:/root/problems:cached
      - ../library:/root/library:cached
      - ../atcoder-cli-nodejs:/root/.config/atcoder-cli-nodejs:cached
      - ../.local:/root/.local:cached
      - ../.vscode:/root/.vscode:cached

#    # オプション これらのconfigファイルが必要なければコメントアウト
#      - ../dotfiles/.zshrc:/root/.zshrc
#      - ../dotfiles/.zinit:/root/.zinit
#      - ../dotfiles/.zsh_history:/root/.zsh_history
#      - ../dotfiles/.aliases:/root/.aliases

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
